---
language: python
python: "2.7"

before_install:
  # Make sure everything's up to date.
  - sudo apt-get update -qq

install:
  # Install Ansible.
  - pip install ansible

  # Add ansible.cfg to pick up roles path. and inventory file
  - echo -e '[defaults]\nroles_path = ../' > ansible.cfg
  - echo 'localhost  ansible_connection=local' > tests/local.ini

script:
    # 1st: check syntax
    - echo "***************************** SYNTAX CHECK (1) *****************************"
    - ansible-playbook -i tests/local.ini tests/test1.yml --syntax-check
    # 2nd:  Make sure we run the entire playbook
    - echo "***************************** RUN PLAY (2) *****************************"    
    - ansible-playbook -i tests/local.ini tests/test1.yml --sudo -vvvv
    # 3rd:  Make sure our playbook is idempotent 
    - echo "***************************** Idempotence test (3) *****************************"     
    - >
      ansible-playbook -i tests/local.ini tests/test1.yml --sudo -vvvv | tee ansible_output  
      | grep -q 'changed=0.*failed=0'
      && (echo 'Idempotence test: pass' && exit 0)
      || (echo 'Idempotence test: fail' && exit 1)
    # 4th:  Application test (TODO)

after_failure:
    - echo -e "\e[31m######IdepotanceLog #######\e[0m" 
    - sudo cat ansible_output
    - echo -e "\e[31m######Syslog#######\e[0m"
    - sudo cat /var/log/syslog
    - echo -e "\e[31m######NerveLog#######\e[0m" 
    - sudo cat /var/log/smartstack/nerve.log  
    - echo -e "\e[31m######SerfLog#######\e[0m"
    - sudo cat /var/log/smartstack/serf.log  
    - echo -e "\e[31m######SyanpaseLog#######\e[0m"
    - sudo cat /var/log/smartstack/synapse.log
    - echo -e "\e[31m######AnsibleFacts#######\e[0m"    
    - ansible -i 127.0.0.1, -m setup all -c local

