---
language: python
python: "2.7"

before_install:
  # Make sure everything's up to date.
  - sudo apt-get update -qq

install:
  # Install Ansible.
  - pip install ansible

  # Add ansible.cfg to pick up roles path. and inventory file
  - "printf '[defaults]\nroles_path = ../' > ansible.cfg"
  - "printf 'localhost  ansible_connection=local' > local.ini"
script:
    # 1st: check syntax
    - ansible-playbook -i local.initests/test1.yml --syntax-check

    # 2nd:  Make sure we run the entire playbook
    - ansible-playbook -i local.ini tests/test1.yml --sudo

    # 3rd:  Make sure our playbook is idempotent 
    - >
      ansible-playbook -i local.ini tests/test1.yml --sudo
      | grep -q 'changed=0.*failed=0'
      && (echo 'Idempotence test: pass' && exit 0)
      || (echo 'Idempotence test: fail' && exit 1)

    # 4th:  Application test (TODO)
    #- ./tests/test_logs.sh