---
# tasks file for ansible-smartstack

- name: nerve | Get nerve from git
  git:
      repo="{{nerve_repository}}"
      dest="{{nerve_install_dir}}"
      force=no
      version="{{nerve_reference}}"
      accept_hostkey=true
  sudo_user: "{{smartstack_user}}"

- name: nerve | Install nerve
  shell: bundle install --without development 
  args:
    chdir: "{{nerve_install_dir}}"
  environment: smartstack_env_variable
  register: nerve_bundle_install
  changed_when: nerve_bundle_install.stdout.find('Installing') != -1
  sudo_user: "{{smartstack_user}}"

  #Maybe include in common only rather in synapse and nerve
- name: nerve | Include services variable file
  include_vars: "{{smartstack_services_files}}"
  when: smartstack_services_files is not false

- name: nerve | Deploy configuration file
  template:
    src=nerve/nerve_config.json.j2
    dest="{{nerve_home}}/config.json"
    mode=0640
    owner="{{smartstack_user}}" 
    group="{{smartstack_user}}"
  notify: restart nerve

- name: nerve | Deploy start script
  template:
    src=nerve/nerve_start.sh.j2
    dest="{{nerve_home}}/nerve_start.sh"
    mode=0755

- name: nerve | Configure nerve log rotation
  template:
    src=nerve/nerve_log_rotation.j2
    dest=/etc/logrotate.d/nerve

- name: nerve | Deploy init.d script
  template:
    src=nerve/nerve_init.sh.j2
    dest="/etc/init.d/nerve"
    mode=0755

- name: nerve | Ensure nerve is running
  service: 
    name=nerve
    state=started
    enabled=true   