---

- name: omnibus | Create base source directory
  file: 
   path="{{ smartstack_omnibis_src }}"
   owner="{{ smartstack_user }}"
   group="{{ smartstack_user }}"
   mode=0755
   state=directory

- name: omnibus | Get binary
  get_url: 
    url="{{ smartstack_omnibis_url }}"
    dest="{{ smartstack_omnibis_src }}"
    sha256sum="{{ smartstack_omnibis_sha256 | default(omit) }}"
  register: omnibus_download

  # ubuntu specific 
- name: omnibus | Check if smartstack is installed
  command: dpkg-query -W smartstack
  register: omnibus_smartstack_check_deb
  failed_when: omnibus_smartstack_check_deb.rc > 1
  changed_when: omnibus_smartstack_check_deb.rc == 1

- name: omnibus | Install omnibus deb
  apt: 
    deb="{{ smartstack_omnibis_src }}/{{ omnibus_packagename |default(smartstack_omnibis_url | basename) }}"
  when: omnibus_smartstack_check_deb.rc == 1