---
# handlers file for ansible-smartstack

- name: restart synapse
  service: 
    name=synapse
    state=restarted
    enabled=true

- name: restart nerve
  service: 
    name=nerve
    state=restarted
    enabled=true

- name: restart serf
  service: 
    name=serf
    state=restarted
    enabled=true    