---

services_ports                    : 
                                      synapse        : 3210
                                      nerve          : 3211
                                      haproxy        : 3212
                                      mysql          : 3306
                                      sqlslave       : 3402
                                      memcache       : 3403
                                      postgresql     : 5432

services   :
   memcache: 
        synapse : 
              discovery          : 
                method    : "serf"
              haproxy            :
                server_options   : "check inter 1s rise 1 fall 1"
                listen           :
                                   - "mode tcp"
                port             : "{{ services_ports.memcache }}"
        nerve :
              port               : "{{ services_ports.memcache }}"
              reporter_type      : "serf"
              check_interval     : 1
              checks:
                 - type     : "tcp"
                   timeout  : 1
                   rise     : 2
                   fall     : 3
   postgresql: 
        synapse : 
              discovery          : 
                method    : "serf"
              haproxy            :
                server_options   : "check inter 10s fastinter 5s downinter 8s rise 3 fall 2"
                listen           :
                                   - "mode tcp"
                                   - "timeout  connect 10s"
                                   - "timeout  client  1h"
                                   - "timeout  server  1h"
                port              : "{{ services_ports['postgresql'] }}"
        nerve:
              port               : "{{ services_ports['postgresql'] }}"
              reporter_type      : "serf"
              check_interval     : 3
              checks:
                 - type     : "tcp"
                   timeout  : 5
                   rise     : 2
                   fall     : 2                   
   sqlslave: 
        synapse : 
              discovery          : 
                method    : "serf"
              haproxy            :
                server_options   : "check inter 10s fastinter 5s downinter 8s rise 3 fall 2"
                listen           :
                                   - "mode tcp"
                                   - "timeout  connect 10s"
                                   - "timeout  client  1h"
                                   - "timeout  server  1h"
                port              : "{{ services_ports.sqlslave }}"
        nerve:
              port               : "{{ services_ports.sqlslave }}"
              reporter_type      : "serf"
              check_interval     : 3
              checks:
                 - type     : "tcp"
                   timeout  : 5
                   rise     : 2
                   fall     : 2
